name: rise_pathway
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15

  # Charts
  fl_chart: ^0.69.0

  cupertino_icons: ^1.0.6

  # State management
  get: ^4.6.6
  go_router: ^14.2.7

  # SVG / Images
  flutter_svg: ^2.0.10+1

  # Text

  # UI
  flutter_chat_ui: ^1.6.15

  # Animate
  flutter_animate: ^4.5.0

  # Icons

  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # Config
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  sqlite3: ^2.4.6
  dartz: ^0.10.1

  # Uitls
  intl: ^0.19.0
  pinput: ^5.0.0
  logger: ^2.4.0
  path_provider: ^2.1.4
  iconify_design: ^1.0.1
  appinio_swiper: ^2.1.1
  table_calendar: ^3.1.2
  flutter_chat_types: ^3.6.2
  flutter_easyloading: ^3.0.5
  flutter_card_swiper: ^7.0.1
  fluentui_system_icons: ^1.1.257
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.3+1
  flutter_widget_from_html: ^0.15.2
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/container_assets/
    - assets/mood_rate/
    - assets/nav_bar_icons/
    - assets/gif/
    - assets/svg/
    - assets/svg/login_svgs/
    - assets/svg/quiz_page/
    - assets/png/
    - assets/imgs/
    - lib/.env
    - assets/music/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
