// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_HkE5M3uE-wi35r-jLdTGJW_ArSnVGE',
    appId: '1:296052683450:web:55a1be1b50f79db16dc883',
    messagingSenderId: '296052683450',
    projectId: 'fantasy-banking-app',
    authDomain: 'fantasy-banking-app.firebaseapp.com',
    storageBucket: 'fantasy-banking-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvBFIl0CZPnEspJ5PhPb0J7iq582e1ao',
    appId: '1:296052683450:android:e7110484e9f1636c6dc883',
    messagingSenderId: '296052683450',
    projectId: 'fantasy-banking-app',
    storageBucket: 'fantasy-banking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KQSWXDhRn62b7_U-usxYgj8BGLN3tFw',
    appId: '1:296052683450:ios:04d51b8cc51cdbc36dc883',
    messagingSenderId: '296052683450',
    projectId: 'fantasy-banking-app',
    storageBucket: 'fantasy-banking-app.appspot.com',
    iosBundleId: 'com.example.fcfsBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KQSWXDhRn62b7_U-usxYgj8BGLN3tFw',
    appId: '1:296052683450:ios:26cb22555aab5dd16dc883',
    messagingSenderId: '296052683450',
    projectId: 'fantasy-banking-app',
    storageBucket: 'fantasy-banking-app.appspot.com',
    iosBundleId: 'com.example.fcfsBankingApp.RunnerTests',
  );
}
